language: java

deploy:
  provider: releases
  api_key: $API_KEY
  file: target/stashNotifier.hpi
  skip_cleanup: true
  on:
    tags: true

# Requires user input
#after_deploy:
#  - mvn release:prepare release:perform -Dusername=$JENKINS_USERNAME -Dpassword=$JENKINS_PASSWORD